"""Markdown rendering for Signal and MacroContext."""

from __future__ import annotations

from .schema import MacroContext, Signal


def render_signal_markdown(sig: Signal) -> str:
    """Render a Signal as Markdown."""
    lines = []
    lines.append(f"# Signal: {sig.title or sig.id or '(untitled)'}")
    lines.append("")

    if sig.id:
        lines.append(f"**ID:** {sig.id}")
    if sig.source_task:
        lines.append(f"**Source:** {sig.source_task}")
    if sig.signal_type:
        lines.append(f"**Type:** {sig.signal_type}")
    lines.append(f"**Action Level:** {sig.action_level.value}")
    lines.append(f"**Confidence:** {sig.confidence}/100")
    lines.append(f"**Direction:** {sig.direction.value}")
    if sig.impact_horizon:
        lines.append(f"**Impact Horizon:** {sig.impact_horizon}")
    lines.append(f"**Data Quality:** {sig.data_quality.value}")
    if sig.suggested_action:
        lines.append(f"**Suggested Action:** {sig.suggested_action}")
    lines.append("")

    if sig.summary:
        lines.append("## Summary")
        lines.append(sig.summary)
        lines.append("")

    if sig.instrument:
        inst = sig.instrument
        lines.append("## Instrument")
        lines.append(f"- **Code:** {inst.code}")
        if inst.name:
            lines.append(f"- **Name:** {inst.name}")
        lines.append(f"- **Asset Type:** {inst.asset_type.value}")
        lines.append("")

    if sig.evidence:
        lines.append("## Evidence")
        for i, e in enumerate(sig.evidence, 1):
            lines.append(f"### Evidence {i} [{e.evidence_level.value}]")
            lines.append(f"- **Source:** {e.source}")
            if e.date:
                lines.append(f"- **Date:** {e.date}")
            if e.quote_or_data:
                lines.append(f"- **Data:** {e.quote_or_data}")
            if e.url:
                lines.append(f"- **URL:** {e.url}")
            if e.note:
                lines.append(f"- **Note:** {e.note}")
            lines.append("")

    if sig.trigger_condition or sig.invalidation_condition or sig.max_risk or sig.risk_note:
        lines.append("## Risk & Conditions")
        if sig.trigger_condition:
            lines.append(f"- **Trigger:** {sig.trigger_condition}")
        if sig.invalidation_condition:
            lines.append(f"- **Invalidation:** {sig.invalidation_condition}")
        if sig.max_risk:
            lines.append(f"- **Max Risk:** {sig.max_risk}")
        if sig.risk_note:
            lines.append(f"- **Risk Note:** {sig.risk_note}")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by invest-signal-kit. Not investment advice.*")
    return "\n".join(lines)


def render_macro_markdown(ctx: MacroContext) -> str:
    """Render a MacroContext as Markdown."""
    lines = []
    lines.append(f"# Macro Context: {ctx.date or '(no date)'}")
    lines.append("")

    if ctx.source_task:
        lines.append(f"**Source:** {ctx.source_task}")
    if ctx.risk_appetite:
        lines.append(f"**Risk Appetite:** {ctx.risk_appetite}")
    if ctx.market_regime:
        lines.append(f"**Market Regime:** {ctx.market_regime}")
    lines.append("")

    if ctx.summary:
        lines.append("## Summary")
        lines.append(ctx.summary)
        lines.append("")

    if ctx.key_variables:
        lines.append("## Key Variables")
        for v in ctx.key_variables:
            lines.append(f"### {v.name}")
            if v.change:
                lines.append(f"- **Change:** {v.change}")
            lines.append(f"- **Confidence:** {v.confidence}/100")
            lines.append(f"- **Data Quality:** {v.data_quality.value}")
            if v.possible_affected_themes:
                lines.append(f"- **Affected Themes:** {', '.join(v.possible_affected_themes)}")
            if v.source:
                lines.append(f"- **Source:** {v.source}")
            lines.append("")

    if ctx.notes_for_tasks:
        lines.append("## Notes for Downstream Tasks")
        for n in ctx.notes_for_tasks:
            if n.theme:
                lines.append(f"### {n.theme}")
            if n.background:
                lines.append(f"- **Background:** {n.background}")
            if n.what_to_verify:
                lines.append(f"- **Verify:** {n.what_to_verify}")
            lines.append("")

    lines.append("---")
    lines.append("*Generated by invest-signal-kit. Not investment advice.*")
    return "\n".join(lines)
